steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - wrapper/backend/Dockerfile
      - -t
      - $_IMAGE_URI
      - .
    timeout: 1600s

images:
  - $_IMAGE_URI

options:
  machineType: E2_HIGHCPU_8
  diskSizeGb: 30
timeout: 1800s
