services:
  - type: web
    name: ncsu-matching-api
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: APP_STORAGE_DIR
        value: /var/data
      - key: MENTEE_GOOGLE_FORM_ENABLED
        value: "true"
      - key: MENTEE_GOOGLE_FORM_REQUIRED
        value: "true"
      - key: MENTEE_GOOGLE_FORM_RESPONSE_URL
        value: "https://docs.google.com/forms/d/e/1FAIpQLScEp0vvZtkpEtWFxPthh5xbGr0rcEt5k6Zd8CjbTeXHT-VskA/formResponse"
      - key: MENTEE_GOOGLE_FORM_JSON_ENTRY_ID
        value: ""
      - key: MENTOR_GOOGLE_FORM_ENABLED
        value: "true"
      - key: MENTOR_GOOGLE_FORM_REQUIRED
        value: "true"
      - key: MENTOR_GOOGLE_FORM_RESPONSE_URL
        value: "https://docs.google.com/forms/d/e/1FAIpQLScaKH4o1bXtz6rptxuX22C4MMncdPsbaQHsgq-1taXT0Rzm_Q/formResponse"
      - key: MENTOR_GOOGLE_FORM_JSON_ENTRY_ID
        value: ""
    disk:
      name: nlp-matching-storage
      mountPath: /var/data
      sizeGB: 1
